server:
  port: 8081
  
spring:
  application:
    name: fornecedor-service

  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka