server:
  port: 8081
  
spring:
  application:
    name: fornecedor-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fornecedor?createDatabaseIfNotExist=true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
