server:
  port: 8080
  
spring:
  application:
    name: loja-service
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka