server:
  port: 8888
  
spring:
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
          search-locations:
          - C:/Desenv/workspaces/alura-microservice-repo/fornecedor
